### ISSUE TITLE
doesnt build with boost 1.87, asio::io_service removed

### ISSUE THREAD

**Issue by landryb** [PurpleI2P/i2pd#2126]
```
/tmp/pobj/i2pd-2.54.0/i2pd-2.54.0/build/../libi2pd/Timestamp.h:55:17: error: no type \
named 'io_service' in namespace 'boost::asio'  boost::asio::io_service m_Service;
                        ~~~~~~~~~~~~~^
```
the io_service API was deprecated a while ago, and io_context should be used instead. cf https://github.com/boostorg/asio/issues/110

**Comment by orignal** [comment]
1.87 is still beta. If it's removed completely without a workaround it will break too many projects.

**Comment by lgv5** [comment]
@orignal the amount of work required is quite a lot actually. The upside is that I'm taking care of it, at least in the context of patching 2.54.0 for OpenBSD (we currently have Boost 1.84.0 there, so the current patches aim to make it work for both 1.84.0 and 1.87.0). For a sneak peek, check https://gist.github.com/lgv5/98fe003589ac2e640201fab133817bd2 . That's missing at least changes for the resolver (doing that now).

Once it's ready, I can submit a PR.

**Comment by orignal** [comment]
Fixed in https://github.com/PurpleI2P/i2pd/commit/34745386974845ab3b9e1e2b15c2013f3b2a2f7b

**Comment by lgv5** [comment]
@orignal the gist https://gist.github.com/lgv5/1831ac7c10d6a7de5d8e7e9d825ad69f includes all the work. I'm able to run i2pd 2.54.0 against Boost 1.84.0 and 1.87.0-beta1. The somewhat complete list of changes are:

- boost::asio::io_service became boost::asio::io_context
- boost::asio::io_service::work was removed
- boost::asio::const_buffers_1 was removed
- resolvers required a lot work (query was removed, some iterator was removed)
- async_resolver required changes
- io_service::post() is no more

I'll prepare a PR tomorrow.

**Comment by orignal** [comment]
Fixed with and tested with boost 1.87.
https://github.com/PurpleI2P/i2pd/commit/ffd18baf30d0259f140e74f5c47ff455e54f2dd8

**Comment by khumarahn** [comment]
Hi! Are there any plans for a release where this is fixed, even if it is just 2.54.0 with a couple of extra commits?
I'm asking because I'm selfish: I want an easy way to close gentoo bug https://bugs.gentoo.org/946514

**Comment by orignal** [comment]
It's not "couple of extra commits". We will discuss.

**Comment by khumarahn** [comment]
Thanks :-)

**Comment by orignal** [comment]
Done. https://github.com/PurpleI2P/i2pd/releases/tag/2.55.0

**Comment by khumarahn** [comment]
Amazing, thank you
