### ISSUE TITLE
Can't build on Raspberry Pi

### ISSUE THREAD

**Issue by Faruduvawe** [PurpleI2P/i2pd#429]
I'm not able to build latest (stable and git) i2pd for Debian (Raspbian) against armhf (Raspberry Pi B+).

Short log:
> g++ -g -Wall -std=c++0x -fPIC   -c -o obj/Tunnel.o Tunnel.cpp
> Tunnel.cpp: In member function ‘void i2p::tunnel::Tunnels::AddTransitTunnel(std::shared_ptr<i2p::tunnel::TransitTunnel>)’:
> Tunnel.cpp:408:17: error: ‘class std::unordered_map<unsigned int, std::shared_ptr<i2p::tunnel::TunnelBase> >’ has no member named ‘emplace’
> Tunnel.cpp: In member function ‘void i2p::tunnel::Tunnels::AddInboundTunnel(std::shared_ptr<i2p::tunnel::InboundTunnel>)’:
> Tunnel.cpp:794:17: error: ‘class std::unordered_map<unsigned int, std::shared_ptr<i2p::tunnel::TunnelBase> >’ has no member named ‘emplace’
> Makefile:50: recipe for target 'obj/Tunnel.o' failed
> make: *** [obj/Tunnel.o] Error 1

Full log: [i2pd-build.log.txt](https://github.com/PurpleI2P/i2pd/files/181735/i2pd-build.log.txt)

Raspbian is up-to-date and all dependencies from [build_notes_unix.md](https://github.com/PurpleI2P/i2pd/blob/0e5b32ef13f4678de4d3246aa3dee807e7a840f7/docs/build_notes_unix.md#debianubuntu) are installed.

> Distributor ID:	Debian
> Description:	Debian GNU/Linux 7.9 (wheezy)
> Release:	7.9
> Codename:	wheezy

Latest successfully build was on version i2pd-2.2.0-2.

**Comment by orignal** [comment]
use g++-4.8

**Comment by Faruduvawe** [comment]
@orignal It worked with g++-4.8. I think it should be noted somewhere in ReadMe / Build Notes.

**Comment by orignal** [comment]
We will change it. Thanks
