### ISSUE TITLE
openssl branch

### ISSUE THREAD

**Issue by orignal** [PurpleI2P/i2pd#287]
crypto++ will be officially replaced by openssl by the start of 2016 and that branch will be main one.
All pull requests there will be reviewed and approved by me.

**Comment by zlatinb** [comment]
Good to see this project has returned to active development.  Keep up the good work!

**Comment by orignal** [comment]
Yes, I'm going to make new release soon once I'm done with EdDSA.

**Comment by mlt** [comment]
> I was able to build both openssl and i2pd using mingw-w64

Did you run nasm under wine? Or do you have non-optimized version? I have [this problem](https://mta.openssl.org/pipermail/openssl-dev/2015-August/002470.html) and it looks like [msys perl on Windows is to blame](http://www.magicsplat.com/blog/building-openssl-tls/).

**Comment by orignal** [comment]
I did it under Windows 7. Haven't tried mingw under Linux, that's the next step.

**Comment by mlt** [comment]
It does make a difference even without AES-NI on my older laptop
```
C:\dev\openssl\stage\nasm\bin>openssl.exe speed rsa2048
Doing 2048 bit private rsa's for 10s: 305 2048 bit private RSA's in 9.16s
Doing 2048 bit public rsa's for 10s: 13734 2048 bit public RSA's in 9.52s
OpenSSL 1.1.0-dev xx XXX xxxx
built on: reproducible build, date unspecified
options:bn(64,32) rc4(8x,mmx) des(idx,cisc,2,long) aes(partial) idea(int) blowfish(idx)
compiler: cl  /MD /Ox /O2 /Ob2 -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -wd4090 -Gs0 -GF -Gy -nologo -DOPENSSL_SYS_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_STATIC_ENGINE
                  sign    verify    sign/s verify/s
rsa 2048 bits 0.030020s 0.000693s     33.3   1443.3

C:\dev\openssl\stage\no-asm\bin>openssl.exe speed rsa2048
Doing 2048 bit private rsa's for 10s: 119 2048 bit private RSA's in 9.53s
Doing 2048 bit public rsa's for 10s: 4366 2048 bit public RSA's in 9.41s
OpenSSL 1.1.0-dev xx XXX xxxx
built on: reproducible build, date unspecified
options:bn(64,32) rc4(idx,int) des(idx,cisc,2,long) aes(partial) idea(int) blowfish(idx)
compiler: cl  /MD /Ox /O2 /Ob2 -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -wd4090 -Gs0 -GF -Gy -nologo -DOPENSSL_SYS_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_STATIC_ENGINE
                  sign    verify    sign/s verify/s
rsa 2048 bits 0.080095s 0.002154s     12.5    464.2
```
Strawberry Perl made a difference indeed. Somehow msys perl fail to do things for me.

Also if you are not interested in MSVC++, you might get by with `pacman -S openssl` as mentioned on the link you posted.

**Comment by orignal** [comment]
It you are able to fix MSVS project in Win32 folder for openssl, it would be great. That part is beyond of my knowledge, it was created by @chertov and then adjusted by @kytvi2p later.

**Comment by mlt** [comment]
> fix MSVS project in Win32 folder for openssl

I'm working on CMake, IMHO there is no point maintaining version specific MSVS solutions/projects.

What Boost/OpenSSL are you using? It seems that "older" boost 1.58 won't build with OpenSSL 1.0.2 and newer (I'm using trunk). I'm getting [these errors](https://github.com/chriskohlhoff/asio/issues/74) among others. And I had to build deprecated stuff into OpenSSL. I'm so lazy to update boost.

Also, I'm out of clue why but [this](https://github.com/PurpleI2P/i2pd/blob/openssl/Signature.cpp#L362) freaks out MS compiler. I tried placing *const* in front of size_t len. It didn't help. I wonder why it says "size 0"
```
4>C:\dev\i2pd\i2pd.openssl\Signature.cpp(363): error C2057: expected constant expression
4>C:\dev\i2pd\i2pd.openssl\Signature.cpp(363): error C2466: cannot allocate an array of constant size 0
4>C:\dev\i2pd\i2pd.openssl\Signature.cpp(363): error C2133: 'buf1' : unknown size
```

**Comment by orignal** [comment]
I use boost 1.54 and openssl 1.0.1f from repository.
If there is a problem with boost::asio::ssl I can replace that code to direct call of libssl as I do in C version.  The code is here https://bitbucket.org/orignal/i2pd/src/6e1f730e5f9d/Reseed.cpp .

The issue you found in Signature.cpp seems MSVC specific. If the issue persists, I will fix it. You can specify 'len' as template parameter as workaround

**Comment by orignal** [comment]
The last issue have been fixed

**Comment by mlt** [comment]
Well, I have it built and it runs with a few minor tweaks. I just hard-coded 64 and added assert ;-) 32 bytes of wasted stack memory at times won't hurt. [Apparently it is g++ extension](http://stackoverflow.com/a/15013295/673826), and you'd expect a warning with `-pedantic`.
I checked out `OpenSSL_1_0_1p`. It works okay with boost 1.58. I'll see if I can reduce amount of things changed.

**Comment by orignal** [comment]
Probably it's gcc extension since I copied that code from C version always assuming gcc, since I use gcc atomics there, etc.
Back to MSVC, I just want to build and try it again as I did for crypto++ version. E.g. I have VS2013 installed and want to build and run the project
